### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by FlorianWolters** [128technology/protobuf_dissector#3]
> Then start Wireshark, open a file with your Protobuf packets, select one of those packets, right-click and select "Decode as..." **and scroll down to the name of your outer-most Message type.** To make this happen all the time for a UDP port, go to "Edit->Preferences->Protocols", **fnd your outer-most Message type**, and put the UDP port number in the field shown (or a range of port numbers if it can be more than one port).

What does that mean? I use Wireshark v2.2.7 with Microsoft Windows 10. I am able to capture the Protobuf messages, but unable to use the dissector... Where do I have to "configure" my .proto files?

**Comment by FlorianWolters** [comment]
The `proto` files (only `proto2` syntax is supported, `proto3` does not work) that should be decoded must be added to `%APPDATA%\Wireshark\plugins\protobuf_dissector\files`. They must be placed at the top-level, since the Lua code does not parse the `files` directory recursively. Nonetheless the usage of the dissector is not very easy/user-friendly and/or buggy:
* The visualization at the top (`Protocol` and `Info` columns) displays the wrong message type. I have tested it with multiple nested messages.
* The visualization at the bottom (field decoding) is very verbose, each `message` field has to be separately expanded via a click. This is not very useful, imo.

Nonetheless, it basically works. Therefore I close this issue.

**Comment by qjh-nj** [comment]
> The `proto` files (only `proto2` syntax is supported, `proto3` does not work) that should be decoded must be added to `%APPDATA%\Wireshark\plugins\protobuf_dissector\files`. They must be placed at the top-level, since the Lua code does not parse the `files` directory recursively. Nonetheless the usage of the dissector is not very easy/user-friendly and/or buggy:
> 
> * The visualization at the top (`Protocol` and `Info` columns) displays the wrong message type. I have tested it with multiple nested messages.
> * The visualization at the bottom (field decoding) is very verbose, each `message` field has to be separately expanded via a click. This is not very useful, imo.
> 
> Nonetheless, it basically works. Therefore I close this issue.

Hello! Do you know how to make it work when we use proto3? Where shoud I remake in this plugin? Thanks!
